// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "DZ_G2D+z#]uq9Jbr-)w{":
            case "Nave Espacial 1":return img`
...........d...........
..........d6c..........
.........d966c.........
.........d966a.........
........dcddbba........
......dbbdddddbba......
.....dbbbbbddddbba.....
....dbbccbbbddccbba....
...dbbcfdcbbccdffbba...
..dbbcccfdbbbdfcccbba..
.dbbca454dcdbd454acbba.
dccc.a242fddbf242a.dbba
......a2acdbaca2a......
.......acbdbbbca.......
.......cbba5abbc.......
......cbba555abbc......
......caa24542aac......
......a..a242a..a......
.........ca2ac.........
..........cac..........
...........c...........
`;
            case "image1":
            case "Nave Galaga":return img`
. . . . . . . 1 . . . . . . . 
. . . . . . . 1 . . . . . . . 
. . . . . . . 1 . . . . . . . 
. . . . . . 1 1 1 . . . . . . 
. . . . . . 1 1 1 . . . . . . 
. . . 2 . . 1 1 1 . . 2 . . . 
. . . 2 . . 1 1 1 . . 2 . . . 
. . . 1 . 1 1 1 1 1 . 1 . . . 
. . . 1 . 1 1 1 1 1 . 1 . . . 
2 . . 1 8 1 1 2 1 1 8 1 . . 2 
2 . . 8 1 1 2 2 2 1 1 8 . . 2 
1 . . 1 1 1 2 1 2 1 1 1 . . 1 
1 . 1 1 1 1 1 1 1 1 1 1 1 . 1 
1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 
. . . 2 2 1 1 1 1 1 2 2 . . . 
. . . 2 2 . . 1 . . 2 2 . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Animación Nave 1":
            case "*8bR,5xhb`+Q":return [img`
...........d...........
..........d6c..........
.........d966c.........
.........d966a.........
........dcddbba........
......dbbdddddbba......
.....dbbbbbddddbba.....
....dbbccbbbddccbba....
...dbbcfdcbbccdffbba...
..dbbcccfdbbbdfcccbba..
.dbbc.454dcdbd454.cbba.
dccc..242fddbf242..dbba
.......2fcdbacf2.......
........cbdbbbc........
.......cbbadabbc.......
......cbba515abbc......
......caa24542aac......
......a...242...a......
...........2...........
.......................
.......................
`, img`
...........d...........
..........d6c..........
.........d966c.........
.........d966a.........
........dcddbba........
......dbbdddddbba......
.....dbbbbbddddbba.....
....dbbccbbbddccbba....
...dbbcfdcbbccdffbba...
..dbbcccfdbbbdfcccbba..
.dbbc2555dcdbd5552cbba.
dccc.2454fddbf4542.dbba
......242cdbac242......
.......2cbdbbbc2.......
.......cbbadabbc.......
......cbba515abbc......
......caa45554aac......
......a..24542..a......
..........242..........
...........2...........
.......................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
